- hosts: Kubernetes_Servers
  become: yes
  tasks:
    - name: Docker Installation
      apt:
        name: docker.io
        state: present
        update_cache: true

    - name: install APT  Transport HTTPS
      apt: 
        name: apt-transport-https
        state: present

    # Issue using this in the ansible 2.11 version.  
    # - name: add Kubernetes apt-key for APT repository
    #   apt_key:
    #     url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    #     state: present

    # replace the below module for solve the issue rise above module.
    - name: Add an apt key by id from a keyserver
      ansible.builtin.shell: curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
      args:
        warn: no

    - name: add Kubernetes APT repository
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: 'kubernetes'

    - name: install kubelet
      apt: 
        name: kubelet=1.18.3-00
        state: present
        update_cache: true

    - name: install kubeadm
      apt: 
        name: kubeadm=1.18.3-00
        state: present

- hosts: Kubernetes_Master
  become: yes
  tasks:
  - name: install kubectl
    apt:
      name: kubectl=1.18.3-00
      state: present
      force: yes

- hosts: ClientServers
  become: yes
  tasks:
  - name: install kubectl
    apt:
      name: kubectl=1.18.3-00
      state: present
      force: yes

  